apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-service
  name: identity-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 9096
  selector:
    app: identity-service
